import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About next app",
  description: "Generated by create next app",
};

export default function About() {
  return <h3>Select subitem</h3>;
}
