import TheHeader from "@/components/TheHeader";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, PT_Mono } from "next/font/google";
import TheFooter from "@/components/TheFooter";

const inter = Inter({ subsets: ["latin"] });
const ptMono = PT_Mono({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Test next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ptMono.className}>
        <TheHeader />
        <main className="container">{children}</main>
        <TheFooter />
      </body>
    </html>
  );
}
